import type { Organization, Consent, PermissionEvent } from "./types"

export const organizations: Organization[] = [
  {
    id: "1",
    name: "Google",
    logo: "G",
    accessLevel: ["Email", "Calendar", "Contacts"],
    lastSync: "2024-01-15T10:30:00Z",
    riskLevel: "medium",
    dataTypes: ["personal", "behavioral"],
    description: "Access to Gmail, Calendar, and Contacts for productivity integration",
  },
  {
    id: "2",
    name: "Meta",
    logo: "M",
    accessLevel: ["Profile", "Friends List", "Photos"],
    lastSync: "2024-01-14T08:15:00Z",
    riskLevel: "high",
    dataTypes: ["personal", "behavioral", "location"],
    description: "Social media profile access for social login and sharing features",
  },
  {
    id: "3",
    name: "Spotify",
    logo: "S",
    accessLevel: ["Listening History", "Playlists"],
    lastSync: "2024-01-15T12:00:00Z",
    riskLevel: "low",
    dataTypes: ["behavioral"],
    description: "Music preferences and listening data for personalized recommendations",
  },
  {
    id: "4",
    name: "EduPlatform",
    logo: "E",
    accessLevel: ["Academic Records", "Course Progress"],
    lastSync: "2024-01-13T14:20:00Z",
    riskLevel: "medium",
    dataTypes: ["educational", "personal"],
    description: "Educational platform with access to academic performance data",
  },
  {
    id: "5",
    name: "HealthApp",
    logo: "H",
    accessLevel: ["Health Data", "Activity", "Sleep"],
    lastSync: "2024-01-15T06:00:00Z",
    riskLevel: "high",
    dataTypes: ["health", "behavioral", "location"],
    description: "Health tracking application with sensitive medical information",
  },
  {
    id: "6",
    name: "BankConnect",
    logo: "B",
    accessLevel: ["Transactions", "Account Balance"],
    lastSync: "2024-01-15T09:45:00Z",
    riskLevel: "high",
    dataTypes: ["financial", "personal"],
    description: "Financial aggregator with access to banking information",
  },
  {
    id: "7",
    name: "DeliveryApp",
    logo: "D",
    accessLevel: ["Location", "Order History"],
    lastSync: "2024-01-14T19:30:00Z",
    riskLevel: "medium",
    dataTypes: ["location", "behavioral"],
    description: "Food delivery service with location and ordering data",
  },
  {
    id: "8",
    name: "GovPortal",
    logo: "GP",
    accessLevel: ["ID Verification", "Tax Records"],
    lastSync: "2024-01-10T11:00:00Z",
    riskLevel: "low",
    dataTypes: ["personal", "financial"],
    description: "Government services portal with identity verification",
  },
]

export const consents: Consent[] = [
  {
    id: "c1",
    organizationId: "1",
    organizationName: "Google",
    dataType: "Email Access",
    purpose: "Email integration",
    grantedAt: "2023-06-15T10:00:00Z",
    status: "active",
  },
  {
    id: "c2",
    organizationId: "2",
    organizationName: "Meta",
    dataType: "Profile Data",
    purpose: "Social login",
    grantedAt: "2023-08-20T14:30:00Z",
    status: "active",
  },
  {
    id: "c3",
    organizationId: "3",
    organizationName: "Spotify",
    dataType: "Listening History",
    purpose: "Personalization",
    grantedAt: "2023-09-01T09:00:00Z",
    status: "active",
  },
  {
    id: "c4",
    organizationId: "5",
    organizationName: "HealthApp",
    dataType: "Health Metrics",
    purpose: "Health tracking",
    grantedAt: "2023-11-10T16:00:00Z",
    status: "active",
  },
  {
    id: "c5",
    organizationId: "6",
    organizationName: "BankConnect",
    dataType: "Transaction Data",
    purpose: "Financial management",
    grantedAt: "2023-12-01T12:00:00Z",
    status: "active",
  },
]

export const permissionHistory: PermissionEvent[] = [
  {
    id: "p1",
    organizationId: "1",
    organizationName: "Google",
    organizationLogo: "G",
    dataType: "Email",
    action: "accessed",
    purpose: "Sync new emails",
    timestamp: "2024-01-15T10:30:00Z",
  },
  {
    id: "p2",
    organizationId: "5",
    organizationName: "HealthApp",
    organizationLogo: "H",
    dataType: "Health Metrics",
    action: "accessed",
    purpose: "Daily health sync",
    timestamp: "2024-01-15T06:00:00Z",
  },
  {
    id: "p3",
    organizationId: "2",
    organizationName: "Meta",
    organizationLogo: "M",
    dataType: "Location",
    action: "accessed",
    purpose: "Location-based features",
    timestamp: "2024-01-14T18:45:00Z",
  },
  {
    id: "p4",
    organizationId: "6",
    organizationName: "BankConnect",
    organizationLogo: "B",
    dataType: "Transactions",
    action: "updated",
    purpose: "New permission scope",
    timestamp: "2024-01-14T14:20:00Z",
  },
  {
    id: "p5",
    organizationId: "7",
    organizationName: "DeliveryApp",
    organizationLogo: "D",
    dataType: "Order History",
    action: "granted",
    purpose: "Marketing personalization",
    timestamp: "2024-01-13T20:15:00Z",
  },
  {
    id: "p6",
    organizationId: "4",
    organizationName: "EduPlatform",
    organizationLogo: "E",
    dataType: "Course Progress",
    action: "accessed",
    purpose: "Progress report generation",
    timestamp: "2024-01-13T14:20:00Z",
  },
  {
    id: "p7",
    organizationId: "3",
    organizationName: "Spotify",
    organizationLogo: "S",
    dataType: "Playlists",
    action: "accessed",
    purpose: "Music recommendations",
    timestamp: "2024-01-12T22:00:00Z",
  },
  {
    id: "p8",
    organizationId: "8",
    organizationName: "GovPortal",
    organizationLogo: "GP",
    dataType: "ID Verification",
    action: "revoked",
    purpose: "User requested revocation",
    timestamp: "2024-01-10T11:00:00Z",
  },
]

export const riskData = [
  { name: "Low Risk", value: 2, fill: "var(--color-success)" },
  { name: "Medium Risk", value: 4, fill: "var(--color-warning)" },
  { name: "High Risk", value: 2, fill: "var(--color-destructive)" },
]

export const dataFlowData = [
  { month: "Aug", transfers: 45 },
  { month: "Sep", transfers: 62 },
  { month: "Oct", transfers: 58 },
  { month: "Nov", transfers: 71 },
  { month: "Dec", transfers: 89 },
  { month: "Jan", transfers: 94 },
]
